### ISSUE TITLE
Investigate Sympy for Julia

### ISSUE THREAD

**Issue by alchemyst** [stelmo/Stochastic-Dynamical-Control-Code#1]
It's usually a good idea to reduce the number of dependencies your code has, and you have now included some Matlab code. Consider using [Sympy for Julia](http://mth229.github.io/symbolic.html).

**Comment by stelmo** [comment]
The Matlab script `Linearised_Runge_Kutta.m` was used to find the algebraic equations relating the continuous state space representation of the CSTR to the discrete state space representation for arbitrary linearisation points and time discretisations. Those equations were then used in the Julia scripts independently (copy and pasted) of the Matlab script. However, I recently updated the code (in the folder `src`, module `Reactor.jl`, function `linearise()`) to use the [Bilinear Transform](http://en.wikipedia.org/wiki/Bilinear_transform) instead of Runge Kutta because it is better in terms of stability and much simpler. Thus that specific script will soon be deleted because it is unnecessary. The other scripts are more for testing ideas out and are not directly used.
